import React from 'react';
import { useAppState } from '../context/StateContext';

const Reports = () => {
    const { state, setState } = useAppState();

    if (state.user?.role !== 'admin') {
        return (
            <div className="glass-panel text-center">
                <h1>Access Denied</h1>
                <p>Only administrators can view room reports.</p>
                <button className="btn btn-primary" onClick={() => window.location.hash = '#dashboard'}>Back to Home</button>
            </div>
        );
    }

    const students = (state.users || []).filter(u => u.role === 'student' && u.roomId === state.user.roomId);
    const studentReport = students.map(s => {
        const registeredEvents = (state.events || []).filter(e => e.roomId === state.user.roomId && (e.attendees || []).some(a => String(a.id) === String(s.id)));
        return { ...s, registeredEvents };
    });

    const totalRoomRegistrations = (state.events || [])
        .filter(e => e.roomId === state.user.roomId)
        .reduce((sum, e) => sum + (e.attendees || []).length, 0);

    const handleRemoveStudent = (studentId) => {
        if (!window.confirm('Are you sure you want to remove this student from the room? Their event registrations will also be completely cleared.')) return;
        
        const newUsers = state.users.filter(u => u.id !== studentId);
        const newEvents = state.events.map(ev => {
            if (ev.roomId === state.user.roomId) {
                return { ...ev, attendees: (ev.attendees || []).filter(a => String(a.id) !== String(studentId)) };
            }
            return ev;
        });

        setState(prev => ({ ...prev, users: newUsers, events: newEvents }));
    };

    const handleExportPDF = () => {
        if (typeof window.html2pdf === 'undefined') {
            alert('PDF library is loading or failed to load. Please check your connection.');
            return;
        }
        
        const printContainer = document.createElement('div');
        printContainer.style.padding = '2rem';
        printContainer.style.background = '#ffffff';
        printContainer.style.color = '#0f172a';
        printContainer.style.fontFamily = 'Inter, sans-serif';
        
        printContainer.innerHTML = `
            <h1 style="text-align: center; margin-bottom: 2rem;">Student Directory - Room ${state.user.roomId}</h1>
            <table style="width: 100%; border-collapse: collapse; margin: 0 auto; text-align: left;">
                <thead>
                    <tr style="border-bottom: 2px solid #e2e8f0;">
                        <th style="padding: 1rem;">Student Name</th>
                        <th style="padding: 1rem;">Email Address</th>
                    </tr>
                </thead>
                <tbody>
                    ${students.length === 0 ? '<tr><td colspan="2" style="padding: 2rem; text-align: center;">No students available.</td></tr>' : students.map((s, idx) => `
                        <tr style="border-bottom: 1px solid #f1f5f9; background: ${idx % 2 === 0 ? '#ffffff' : '#f8fafc'};">
                            <td style="padding: 1rem; font-weight: bold;">${s.name}</td>
                            <td style="padding: 1rem; color: #475569;">${s.email || 'N/A'}</td>
                        </tr>
                    `).join('')}
                </tbody>
            </table>
            <p style="text-align: center; margin-top: 2rem; color: #64748b; font-size: 0.8rem;">Generated by Eventify | Total Students: ${students.length}</p>
        `;

        printContainer.style.position = 'absolute';
        printContainer.style.left = '-9999px';
        document.body.appendChild(printContainer);

        const opt = {
            margin: 0.5,
            filename: 'Student_Directory_' + state.user.roomId + '.pdf',
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
        };
        
        window.html2pdf().set(opt).from(printContainer).save().then(() => {
            document.body.removeChild(printContainer);
        });
    };

    return (
        <div className="reports-page">
            <div className="flex justify-between items-center mb-4">
                <div>
                    <h1>Room Registration Report</h1>
                    <p>Comprehensive activity overview for Room: <strong style={{ color: 'var(--primary)' }}>{state.user.roomId}</strong></p>
                </div>
                <button className="btn btn-outline" onClick={() => window.location.hash = '#dashboard'}>← Back to Dashboard</button>
            </div>

            <div className="grid-cards mb-4" style={{ gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem' }}>
                <div className="glass-panel text-center">
                    <h3 style={{ fontSize: '2rem', color: 'var(--accent)' }}>{students.length}</h3>
                    <p style={{ fontWeight: 'bold', marginBottom: 0 }}>Total Students Enrolled</p>
                </div>
                <div className="glass-panel text-center">
                    <h3 style={{ fontSize: '2rem', color: 'var(--primary)' }}>{totalRoomRegistrations}</h3>
                    <p style={{ fontWeight: 'bold', marginBottom: 0 }}>Total Registrations</p>
                </div>
            </div>

            <div className="glass-panel">
                <div className="flex justify-between items-center mb-4">
                    <h2 style={{ margin: 0 }}>Student Activity Breakdown</h2>
                    <button className="btn btn-primary" onClick={handleExportPDF}>📄 Export to PDF</button>
                </div>
                <div className="table-container">
                    <table style={{ width: '100%', minWidth: '800px' }}>
                        <thead>
                            <tr>
                                <th>Student Details</th>
                                <th>Current Profile</th>
                                <th>Registered Events</th>
                                <th className="text-center">Total Count</th>
                                <th className="text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {studentReport.length === 0 ? (
                                <tr><td colSpan="5" className="text-center" style={{ padding: '2rem', color: 'var(--text-secondary)' }}>No students registered in this room yet.</td></tr>
                            ) : (
                                studentReport.map(s => (
                                    <tr key={s.id}>
                                        <td>
                                            <div style={{ fontWeight: 800, fontSize: '1.1rem' }}>{s.name}</div>
                                            <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>{s.email || 'N/A'}</div>
                                        </td>
                                        <td>
                                            <div style={{ fontWeight: 'bold' }}>{s.branch || 'N/A'}</div>
                                            <div style={{ fontSize: '0.8rem' }}>{s.year || 'N/A'} Year</div>
                                        </td>
                                        <td>
                                            {s.registeredEvents.length > 0 
                                                ? s.registeredEvents.map(e => <span key={e.id} className="badge badge-student" style={{ fontSize: '0.7rem', marginRight: '4px' }}>{e.title}</span>)
                                                : <span style={{ color: 'var(--text-secondary)', fontStyle: 'italic' }}>No registrations</span>}
                                        </td>
                                        <td className="text-center">
                                            <span className="badge" style={{ background: 'var(--text-primary)', color: 'white', fontSize: '1rem', padding: '0.4rem 0.8rem' }}>{s.registeredEvents.length}</span>
                                        </td>
                                        <td className="text-right">
                                            <button className="btn btn-outline" style={{ borderColor: 'var(--danger)', color: 'var(--danger)', padding: '0.3rem 0.8rem', fontSize: '0.8rem' }} onClick={() => handleRemoveStudent(s.id)}>Remove</button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default Reports;
